### ISSUE TITLE
API to place InAppMessageSlideup in a specific position within a hierarchy of views

### ISSUE THREAD

**Issue by arcadefire** [Appboy/appboy-android-sdk#138]
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/Android/) and am still experiencing the issue.

## What version of the Braze Android SDK are you using?
3.1.0

## What did you _want to_ do?
I want to be able to display a custom  `InAppMessageSlideup` view within a hierarchy consisting of a `CoordinatorLayout` as root and a `BottomNavigationView` child. 

The goal is slide down the `InAppMessageSlideup` along with the `BottomNavigationView` to anchor at the bottom of the screen, and for that I would like to use a `CoordinatorLayout.Behaviour`.

## What happened instead?
As far as I know from the documentation, there's not API that allows you to place `InAppMessageSlideup` view in a specific position within a hierarchy of views.

**Comment by radixdev** [comment]
Hi @arcadefire ,

It seems like the most straightforward way to accomplish this would be the ability to provide the Braze SDK with a custom view wrapper ([see the default here](https://github.com/Appboy/appboy-android-sdk/blob/master/android-sdk-ui/src/main/java/com/appboy/ui/inappmessage/InAppMessageViewWrapper.java#L123-L194)). That object is the one that takes the in-app message View and handles adding it to the view hierarchy. Your custom `InAppMessageViewWrapper` could just extend the default one so that you only have to override the `open()` and `close()` methods. Is there another API surface you'd like to see here or would that be acceptable?

**Comment by arcadefire** [comment]
Hey @radixdev,

That sounds about what I'd like to achieve. 
Perhaps it could make sense to rename this `open` and `close` methods to something more descriptive? Something like `addViewToHierarchy` and `removeViewToHierarchy`?

**Comment by radixdev** [comment]
Hey @arcadefire ,

We've added this to our backlog. I'll update you with any progress.

**Comment by radixdev** [comment]
Hi @arcadefire ,

This will be released in the next version of the SDK. Thank you for your patience.

**Comment by radixdev** [comment]
Hi @arcadefire ,

Apologies for the delay! This should now be possible using a custom view wrapper. Please see [setCustomInAppMessageViewWrapperFactory](https://appboy.github.io/appboy-android-sdk/javadocs/com/appboy/ui/inappmessage/AppboyInAppMessageManagerBase.html#setCustomInAppMessageViewWrapperFactory-com.appboy.ui.inappmessage.IInAppMessageViewWrapperFactory-) and the changelog for more information. Please let us know if this accomplishes your use-case.

**Comment by arcadefire** [comment]
Thanks @radixdev. I'll have a look on the new API soon.

**Comment by radixdev** [comment]
Hey @arcadefire ,

I'm closing this issue for now. Please let me know if you more thoughts and we'll continue further.
