### ISSUE TITLE
AndroidX support without Jetifier

### ISSUE THREAD

**Issue by martinbonnin** [Appboy/appboy-android-sdk#154]
`android-sdk-ui-x` should use the `androidx.` packages instead of the old support libs.

Version 6.0.0 has a dependency on `com.android.support:support-compat:28.0.0` and this clashes with the androix artifacts if jetifier is not enabled.

Appboy/Braze is the last dependency in our project that relies on the old support libs and we'd very much like to remove jetifier from our builds.

See also https://github.com/Appboy/appboy-android-sdk/issues/107#issuecomment-427476135 for some background.

**Comment by radixdev** [comment]
We're moving over to an aar artifact that is directly jetified in the near future and should obliviate the need for jetifier in your build directly.

Thank you for the issue!

**Comment by radixdev** [comment]
As an update, this is now in QA and should be released in the next update. Thank you for your patience!

**Comment by radixdev** [comment]
Sorry for the wait @martinbonnin .

Directly jetified artifacts are now available in v7.0.0 of our SDK, released today. There's a migration you'll have to do as outlined in our changelog [Release Date](https://github.com/Appboy/appboy-android-sdk/releases/tag/v7.0.0) since the `android-sdk-ui-x` module is now gone in favor of a new module with the same namespace as the rest of the SDK.

Please let me know if this fixes your issue. I'll keep this issue open for a bit until I hear back in case another change is needed.

**Comment by martinbonnin** [comment]
@radixdev looks like `android-sdk-ui` still depends on the non-androidx artifacts:

```
+--- com.appboy:android-sdk-ui:{require 7.0.0; reject _} -> 7.0.0
|    +--- com.android.support:support-compat:28.0.0

```

This triggers the following error:

```
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
        is also present at [androidx.core:core:1.2.0] AndroidManifest.xml:24:18-86 value=(androidx.core.app.CoreComponentFactory).
```

**Comment by radixdev** [comment]
Hi @martinbonnin ,

Please see the [CHANGELOG 7.0.0](https://github.com/Appboy/appboy-android-sdk/blob/4e878113cd3712aa2c6f9eb75fbc6b6df62c2ffa/CHANGELOG.md#added) for the migration steps. The `android-sdk-ui` module still uses the support library so that error is still expected. The jetified version of the module is found using `android-sdk-ui-jetified`.

![image](https://user-images.githubusercontent.com/2373546/79003326-5d238400-7b20-11ea-891a-0d5affd1835c.png)
