### ISSUE TITLE
Push notifications with deeplinks on Android 9+ do not work

### ISSUE THREAD

**Issue by ouchadam** [Appboy/appboy-android-sdk#155]
# Standard Reporting

## What version of the Braze Android SDK are you using?
6.0.0

## What did you do?

Send a push notification to an android 9.0+ client with a deeplink via `deeplink into application`

 - using automatic push registration

## What did you expect to happen?
Upon tapping the push notification, the deeplink to be launched.

## What happened instead?
The app launches the root intent

I've traced the issue back to https://github.com/Appboy/appboy-android-sdk/blob/master/android-sdk-ui/src/main/java/com/appboy/ui/actions/UriAction.java#L210

I was able to get the `startActivities` stack functionality working on android 9+ with this
```kotlin
val targetIntent = Intent(Intent.ACTION_VIEW, Uri.parse("foo://bar"))
val rootIntent = context.packageManager.getLaunchIntentForPackage(context.packageName)!!
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
  rootIntent.removeFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
  targetIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
}
context.startActivities(arrayOf(rootIntent, targetIntent))
```

The issue can be worked around by disabling `com_appboy_push_deep_link_back_stack_activity_enabled`

**Comment by radixdev** [comment]
Hello @ouchadam ,

1. Is your "root intent" a splash screen that launches another activity after some delay? (e.g. using example names `SplashActivity` -> `MainActivity`)
2. If yes for 1. , could you follow https://www.braze.com/docs/developer_guide/platform_integration_guides/android/push_notifications/integration/#customizing-back-stack-behavior and change the back stack activity to the `MainActivity` instead of the `SplashActivity`?
3. When you disable `com_appboy_push_deep_link_back_stack_activity_enabled`, does the deeplink work 100% of the time?
4. Can you provide [verbose logs](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration/#verbose-logging) that capture logs from a fresh start of the application to you reproducing the issue?

And fyi, in the next release, we're adding functionality to more easily customize the behavior (and launch intent flags) of `UriAction`s.

**Comment by ouchadam** [comment]
I forgot to mention below android 9 is fine, the issue only affects 9.0+

1,2. correct, I've tried using the custom backstack class name and the behaviour is the same
3. yep it works every time so far (from my testing the issue is caused by passing multiple intents to `startActivities()` which I assume is related to https://developer.android.com/about/versions/pie/android-9.0-changes-all#fant-required 
4. I'll try and provide a dump after obscuring etc, from an initial glance there's no signs of error

**Comment by radixdev** [comment]
Hi,

In the latest SDK release, you can customize the behavior of the URI action to follow your custom code. Please see https://www.braze.com/docs/developer_guide/platform_integration_guides/android/advanced_use_cases/deep_linking/ for more details

**Comment by radixdev** [comment]
Hey @ouchadam ,

I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.
