### ISSUE TITLE
Huawei initialisation crash

### ISSUE THREAD

**Issue by VikiBonzo** [Appboy/appboy-android-sdk#162]
# Standard Reporting

## What version of the Braze Android SDK are you using?

com.appboy:android-sdk-ui:8.0.1

## What did you do?

I'm initialising Braze with an API key fetched at runtime

## What did you expect to happen?

The API key to be used and the app not to crash

## What happened instead?

The app crashes with a RuntimeException. Here's the stacktrace

```
Huawei P20 lite (HWANE), 3840MB RAM, Android 9
Report 1 of 6

java.lang.RuntimeException: 
  at com.appboy.configuration.AppboyConfigurationProvider.getAppboyApiKey (SourceFile:222)
  at bo.app.ex.<init> (SourceFile:91)
  at com.appboy.Appboy$23.run (SourceFile:289)
  at java.util.concurrent.ThreadPoolExecutor.processTask (ThreadPoolExecutor.java:1187)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1152)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:784)
 ```

## Steps to reproduce

The issue was reported only in Huawei P20 Pro and Lite devices so far. We received 12 crash reports, so it seems to be affecting those devices only. The app crashes at startup, no additional steps required

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?

This is the code snippet we use to initialise Braze. As you can see, we skip braze inizialisation if, for some reason, we can't find a suitable api key. That means that the api key is correctly passed to the AppboyConfig builder, but then something happens internally that triggers the crash.

```
val apiKeyIdentifier = when {
            BuildConfig.APPLICATION_ID == "one" && other_condition -> R.string.braze_api_key_one
            BuildConfig.APPLICATION_ID == "two" && other_condition -> R.string.braze_api_key_two
            BuildConfig.APPLICATION_ID == "three" && other_condition -> R.string.braze_api_key_three
            BuildConfig.APPLICATION_ID == "four" && other_condition -> R.string.braze_api_key_four
            else -> null
        } ?: return

        val apiKey = application.resources.getString(apiKeyIdentifier)
        val appboyConfig = AppboyConfig.Builder()
                .setApiKey(apiKey)
                .build()
        Appboy.configure(application, appboyConfig)

        application.registerActivityLifecycleCallbacks(AppboyLifecycleCallbackListener(true, false))
```

**Comment by radixdev** [comment]
Hi @VikiBonzo ,

That exception only occurs if no API key is provided when attempting to call the SDK. It is not device model specific. From your code, it looks like a potential cause could be the `when -> else -> null` case getting hit, no API key being set at runtime, and some logic later in your code trying to call the SDK which never had an API key set. I would recommend either:

1. Setting a default API key and placing it in `appboy.xml` to guarantee an API key is always set
2. Same as 1., but instead of returning, use that default API key for the runtime setting
3. Gate all calls to the SDK and block them until an API key is set. This can also be accomplished by calling `disableSdk()` and calling `enableSdk()` after setting an API key.
