### ISSUE TITLE
Feedback about versioning

### ISSUE THREAD

**Issue by tasomaniac** [Appboy/appboy-android-sdk#174]
# Standard Reporting

## What version of the Braze Android SDK are you using?

Trying to update from 3.x.x to 10.0.0 or 12.0.0

## What did you do?

We are refactoring how we register push notifications and 3rd part integrations like Appboy. We upgraded from version 3.x.x to 10.0.0 and we saw a drop on number of active users in the dashboard.

## Problem

We realized that major version of the SDK is being updated quite often. I appreciate that you are strictly following semantic versioning. But still, this many breaking changes in such a short amount of time seems too much.

We think it is too risky:
- to stay on the old version
- to update to the latest

**Comment by radixdev** [comment]
Hi @tasomaniac ,

Firstly, thank you for the feedback! I'll pull back the curtain a bit here. In the past we did not strictly adhere to semantic versioning and would include breaking changes in minor version updates. However we got feedback at that time that some of the breaking changes were missed when upgrading, causing issues of their own. As a result, we then moved towards a strict adherence of semantic versioning, like you've seen, in order to not have integrators miss a breaking change.

Part of the issue is what constitutes a "breaking change". To me, a breaking change is either a major behavioral change in how the SDK operates or a change in the code such that updating the version would result in a developer having to make code changes to avoid compiler errors. Since we're a java (with kotlin interop) SDK, interface additions or changes would constitute a breaking change as well. 

Additionally, since we try to address client issues as rapidly as possible and augment the integrator experience for the better, this sometimes means an interface needs to be updated in order to address it. Breaking changes in version 10.0.0 of the SDK is a prime example of updating that integrator experience for the better. Breaking changes in 8.0.0 are an example of interface changes, that while although might not affect most clients, still justified a major update for the potential of requiring developer work more downstream.

A potential change we could make is lowering the threshold for what constitutes a "breaking" change. For example, the breaking changes in 12.0.0, 8.0.0, 7.0.0, 5.0.0, and 4.0.0 could have been minor version updates since they didn't "break" behavior and were mostly interface changes. True large scale breaking behavioral changes (like updating to AndroidX/Java8 or changing In App Message behavior) are more rare.

Our goal with the strict semantic versioning was to communicate any potential hurdles an integrator might face upon upgrading and to limit surprises. Internally, we can try moving interface changes to their own section of changelog updates and not increase the major version solely because of them. We would also welcome any other feedback or ideas you have on this :)

----------

On the `we saw a drop on number of active users in the dashboard` front, we haven't seen that issue reported elsewhere as a result of SDK upgrading. I would recommend emailing support@braze.com so we can take a more comprehensive look. Or if you have steps to reproduce, please drop them here.

Thanks!
Julian

**Comment by tasomaniac** [comment]
I understand. Thanks for the detailed explanation. In our perspective, it is scary to have major upgrades every month. If we don't do Appboy for couple months, it is ~5 major updates to upgrade. In such cases, we would need to have a very detailed testing.

**Comment by radixdev** [comment]
Ah, thank you for that perspective. I'm going to advocate that we put pure interface changes into their own section and only bump the minor version. That way, major updates are truly major and not just interface changes.

**Comment by tasomaniac** [comment]
Thanks. That makes sense. For the other issue, we're investigating. Unfortunately it is impossible to reproduce and it takes whole release to see how the changes affects.

In our local testing tho, we observed a behavior where our user was not visible in the dashboard as registered but was still be able to receive push notifications just fine.
