### ISSUE TITLE
Flush braze events before wiping data

### ISSUE THREAD

**Issue by sarthakvoi** [Appboy/appboy-android-sdk#178]
* [Y] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration/) and am still experiencing the issue.

## What version of the Braze Android SDK are you using?
Android sdk v11.0.0

## What did you do?

When user selects logout option, execute these in order:

- Fire an event, say: LOGOUT
- invoke `Appboy.getInstance(context).requestImmediateDataFlush()`
- invoke `Appboy.wipeData(context)`

## What did you expect to happen?

'LOGOUT' event should get fired and be visible on the dashboard.

## What happened instead?

No event getting fired.
(Most likely because wipeData call seems to be executed on the current thread and before requestImmediateDataFlush() could trigger the event on the executor thread)

## Why do I want to wipe the data on logout?

Because we are using braze push notifications as well, and seems that even if the user logouts, the user still receives a push notification on their phone (unless we invoke `Appboy.wipeData(context)`), which is a privacy concern for users.
Maybe there are other ways to prevent this from happening?

**Comment by radixdev** [comment]
Instead of calling `wipeData()`, you can instead set the push subscription status to `unsubscribed`, https://www.braze.com/docs/developer_guide/platform_integration_guides/android/analytics/setting_custom_attributes/#setting-up-user-subscriptions

About `wipeData()`, yes that method is fired outside of any executor logic that the SDK normally runs on to ensure its timely execution. From its javadoc "Note that any in-flight actions etc. will be cancelled as a result of this call." If you still need to call `wipeData()` after logging, I would recommend invoking on a short delay after a data flush.

**Comment by sarthakvoi** [comment]
@radixdev Thanks for the prompt reply. 🙇‍♂️ 
The problem that I foresee is that we never subscribe to push notifications, these are mainly being used by braze to fire content cards. Do you think unsubscribing will still work?

And regarding adding a delay, since there will always be some probability of the code failing, I would like to avoid this approach.

**Comment by radixdev** [comment]
> The problem that I foresee is that we never subscribe to push notifications
On Android, users are automatically `subscribed` to push notifications if you do nothing else.

> these are mainly being used by braze to fire content cards. Do you think unsubscribing will still work?
I don't understand what you're saying here. By unsubscribing, a device will not receive a push notification from a campaign, which sounds like the goal you're trying to reach.

**Comment by sarthakvoi** [comment]
@radixdev yeah checked it today, it's working as you mentioned. Thanks for all your help 😄
