### ISSUE TITLE
App freezes while trying to redirect user to web URL

### ISSUE THREAD

**Issue by amit3vedi** [Appboy/appboy-android-sdk#182]
* [x] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration/) and am still experiencing the issue.
* [ ] I have an ANR related issue and have filled out the "ANR Reporting" section below.

# Standard Reporting

## What version of the Braze Android SDK are you using?

13.0.0

## What did you do?

redirect to web URL when user click on notification button

## What did you expect to happen?

user should be redirected to web URL

## What happened instead?

- App is not starting and user is not redirected to specified URL 
- this only happens if we set setHandlePushDeepLinksAutomatically(false) during configuration

## Steps to reproduce
- setHandlePushDeepLinksAutomatically(false) during configuration
- add notification buttons in push notification and set `Open App` or `Redirect to Web URL` as action and send push notification to user
- when you click on notification action button app will freeze
 

## Project that demonstrates the issue

# ANR Reporting

**Comment by radixdev** [comment]
Hi @amit3vedi ,

`setHandlePushDeepLinksAutomatically()` being false means that the host application is in charge of handling the deeplink and not the SDK automatically. So the app not following the deeplink automatically is expected behavior. However, this is another edge case bug in our notification action button handling logic you've found that we should have a fix released for very shortly. Thank you again for filing!

**Comment by radixdev** [comment]
Hi @amit3vedi ,

This has been fixed in the latest release, 13.1.2. Please let me know if this alleviates the apparent "freezing" of the app.

**Comment by amit3vedi** [comment]
@radixdev this issue seems to have resolved in 13.1.2. Thank you
