### ISSUE TITLE
[Bug]: Failed to transform android-sdk-ui-13.1.2

### ISSUE THREAD

**Issue by MohamedISoliman** [Appboy/appboy-android-sdk#219]
### Braze Android SDK Version

13.1.2

### Steps To Reproduce

building the app with android-sdk-ui-13.1.2 is always fail with error:

```
> Could not resolve all files for configuration ':'.
   > Failed to transform android-sdk-ui-13.1.2.aar (com.appboy:android-sdk-ui:13.1.2) to match attributes {artifactType=enumerated-runtime-classes, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Execution failed for AarToClassTransform: /Users/mohamedisoliman/.gradle/caches/transforms-3/045e9c32cb9ff7a042a9d03ac3675f00/transformed/jetified-android-sdk-ui-13.1.2.aar.
         > zip END header not found
   > Failed to transform android-sdk-base-13.1.2.aar (com.appboy:android-sdk-base:13.1.2) to match attributes {artifactType=enumerated-runtime-classes, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AarToClassTransform: /Users/mohamedisoliman/.gradle/caches/transforms-3/70b4135fe31c0db404b83630c0d922ba/transformed/jetified-android-sdk-base-13.1.2.aar.
         > zip END header not found
```

### Expected Behavior

Build should pass.

### Actual Incorrect Behavior

app doesn't build

**Comment by radixdev** [comment]
Hi @MohamedISoliman ,

- Can you provide more details on steps to reproduce? 
- Are you attempting to use the `jetifier` tool on the 13.1.2 AAR? As of [SDK 10.0.0](https://github.com/Appboy/appboy-android-sdk/blob/master/CHANGELOG.md#1000), the SDK doesn't require jetifier since all dependencies are on AndroidX.
- Can you provide a gradle configuration or small sample project that demonstrates this issue (only if you're not attempting to jetify the artifact)
