### ISSUE TITLE
Android 2.3.x in-app messages auto close even if set to wait for user to dismiss

### ISSUE THREAD

**Issue by yishai-glide** [Appboy/appboy-android-sdk#33]
when creating an in-app message campaign, even if the message is set to wait for user to click or dismiss, on devices running Android 2.3.x message auto dismisses after a few seconds (4-5)

**Comment by briancaw** [comment]
Thanks for reporting Yishai - we'll investigate and will update with details regarding a solution in the near future.

**Comment by briancaw** [comment]
Hi Yishai

This is actually by-design; you can see the comment in https://github.com/Appboy/appboy-android-sdk/blob/master/android-sdk-ui/src/com/appboy/ui/slideups/SlideupViewWrapper.java that describes this behavior, and we'll be updating our dashboard composer to inform users that this happens.

The limitation comes from the fact that we use code that leverages the http://developer.android.com/reference/android/view/ViewPropertyAnimator.html which is only available in API 12 and up.  We'll check around if there are any other suitable ways to achieve this functionality that have come about since our initial implementation; otherwise it might have to remain as a shortcoming by-design, and hopefully will have minimal impact as the number of devices using APIs < 12  continues to dwindle.

Thanks again for reporting and we're happy to hear any further comments/questions regarding this behavior.

**Comment by briancaw** [comment]
Hi again @yishai-glide 

We've looked into this a bit and found that we can decently approximate this functionality in older API levels and we'll be adding that update to the SDK in the next release..  Thanks again for reporting this and we look forward to releasing the update in the near future.

**Comment by yishai-glide** [comment]
thank you very much.

looking forward for this to be released

**Comment by briancaw** [comment]
Hi @yishai-glide, this update is released in 1.6.2.  Please let us know if you have any other feedback on this feature.  Thanks again for raising the issue.

**Comment by yishai-glide** [comment]
thanks

On Tue, Mar 17, 2015 at 7:43 PM, briancaw <notifications@github.com> wrote:

> Hi @yishai-glide <https://github.com/yishai-glide>, this update is
> released in 1.6.2. Please let us know if you have any other feedback on
> this feature. Thanks again for raising the issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Appboy/appboy-android-sdk/issues/33#issuecomment-82494933>
> .
>



-- 

Have a great day.

Yishai Levenglick
Android-dev team
Glide Talk Ltd.
