### ISSUE TITLE
AppboyFeedFragment as nested fragment and compatible with CoordinatorLayout

### ISSUE THREAD

**Issue by pgreze** [Appboy/appboy-android-sdk#48]
I'm using a ViewPager inside a Fragment with each tab associated with a nested fragment (getChildFragmentManager).
Sadly, I can't add AppboyFeedFragment as a child because you're using setRetainInstance ([not recommended with UI fragments](http://stackoverflow.com/a/15066467/5489877))

Second issue is with CoordinatorLayout, which is not compatible with ListView.
A temporary solution is to use setNestedScrollingEnabled but it's only working with Android Marshmallow. A better solution would be to use RecyclerView.

There is my quick workaround to fix these 2 issues:

```java
public class FeedFragment extends AppboyFeedFragment {

    @Override
    public void setRetainInstance(boolean retain) {
        super.setRetainInstance(retain && getParentFragment() == null);
    }

    @Override
    public View onCreateView(LayoutInflater layoutInflater, ViewGroup container, Bundle savedInstanceState) {
        View view = super.onCreateView(layoutInflater, container, savedInstanceState);
        ViewCompat.setNestedScrollingEnabled(view.findViewById(android.R.id.list), true);
        return view;
    }
}
```

Sadly, ViewCompat.setNestedScrollingEnabled is not working with Android <= 5.0

**Comment by briancaw** [comment]
Hey @pgreze,

Thanks very much for reporting this.  We're actively investigating and we'll update with our plans for addressing this issue in the near future (I expect we'll have a plan of action by EOD, or Monday).

Thanks,
Appboy Android Team

**Comment by Bucimis** [comment]
Hey @pgreze, thanks for waiting.

1) re: retainInstance, did you notice any negative side effects (slowness, crashes, etc.) from having retainInstance set to true?  Although it's possible to set retain instance to false without negative effects to the user, our impression counting logic will not perform well after an orientation change due to lost state and there will be a small performance penalty due to unnecessary instantiations.  If you are comfortable with that, your current solution should work well.  We are actively exploring using onSaveInstanceState() in a future release to allow users to set retainInstance to false without affecting impression counting.

2) re: nesting scrolling, we're exploring using NestedScrollView or RecyclerView to allow backwards-compatible nested scrolling.  In the meantime, for API levels under 21, we recommend using a separate (non-nested) layout for the portion of your app containing AppboyFeedbackFragment.

**Comment by Bucimis** [comment]
Hey @pgreze,

Were you able to work around the issues you saw?  We have issues for both items open in our public repo but would like to close here for now.

**Comment by pgreze** [comment]
I was able to use your fragment with my workaround, so I'll close this ticket.
But I think this issue is probably important because more and more Android apps are adopting a tabs or bottom bar mechanism with a ViewPager IMHO.

Thanks for your help.

**Comment by Bucimis** [comment]
Hi @pgreze 

Our most recent release `1.14.0` removes `setRetainInstance(true)` from the News Feed, which can now safely be used in nested fragments.

Thanks and cheers,
Appboy Android Team
