### ISSUE TITLE
Better Proguard Rules

### ISSUE THREAD

**Issue by MichaelEvans** [Appboy/appboy-android-sdk#54]
In 1.13.3 you added consumer proguard rules - but they aren't really good ones. Rules like `-keep class com.appboy.** { *; }` keeps everything in the com.appboy namespace - which means that features that might not be used cannot be stripped by proguard.

**Comment by Bucimis** [comment]
Hi @MichaelEvans,

Thanks for pointing this out. Our blanket `keep` rules are intended to ensure that client stack traces are readable by us at the cost of a small amount of optimization (~40kB for a typical APK). We've previously considered this tradeoff worthwhile but agree that doing so may not make sense in all cases, particularly for advanced customers who are responsible enough to store their release mapping files in source control :)

Because of that we'll investigate removing our automated `keep` statement scope in a future release and will keep you posted.

Thanks,
Appboy Android Team

**Comment by Bucimis** [comment]
Hi @MichaelEvans,

Our most recent release `1.14.0` removes the `keep` statements from our automatic Proguard configuration.  Check out https://github.com/Appboy/appboy-android-sdk/blob/master/android-sdk-ui/appboy-proguard-rules.pro for the latest configuration.

Thanks for bringing this issue to our attention!

Cheers,
Appboy Android Team

**Comment by briancaw** [comment]
Hi @MichaelEvans 

If you have any further comments/questions regarding this issue, please feel free to update or re-open this issue.  Thanks again for raising this issue.
