### ISSUE TITLE
Is GET_ACCOUNTS Permission Still Needed?

### ISSUE THREAD

**Issue by sdoward** [Appboy/appboy-android-sdk#56]
[Your documentation](https://www.appboy.com/documentation/Android/#push-notifications) suggests that GCM requires `<uses-permission android:name="android.permission.GET_ACCOUNTS" />` . However [google documentation](https://developers.google.com/cloud-messaging/android/client#manifest) doesn't mention it at all. I believe this requirement was removed.

Is appbody documentation out of date or is this permission required for another reason?

**Comment by Bucimis** [comment]
Hi @sdoward, 

Thanks for getting in touch.  `GET_ACCOUNTS ` is required because we use the framework method of registration that requires at least one Google account on the phone on devices running Ice Cream and below.  We prefer this registration method because it avoids creating a Google Play Services dependency in Appboy.  Note that devices running Jelly Bean and above do not need the permission in their Manifest.

Now that both framework and Google Play Services registration are deprecated (but still functional), we're evaluating moving to FCM for push at which point the permission requirement will disappear. See https://github.com/Appboy/appboy-android-sdk/issues/53 for more context and future updates.

Thanks,
Appboy Android Team

**Comment by briancaw** [comment]
Hi @sdoward,

If you have any further questions please feel free to update or re-open this issue.

Thanks,
Appboy Android Team
