### ISSUE TITLE
Displaying IAM within a DialogFragment

### ISSUE THREAD

**Issue by ernestkamara** [Appboy/appboy-android-sdk#68]
I am testing an on-boarding feature with Appboy IAM, but doesn't seem to work as expected even after reading through #57.
I have a single `FragmentActivity` which initialise the Appboy instance as suggested in the documentation, a browse fragment with a list of items and a `DialogFragment` as detail page.  
I have two action based IAMs campaigns and both IAMs are said to be cached when the app starts as seen in the Log output.

Expected behaviour:
Show first IAM after user accepts terms of service (works fine)
Show second IAM when detail page previewed for the first time. (not working when in the detail page, but on exiting)

I am not sure but does this have to do with the use of `DialogFragment`?
If not how can i display IAM on within a `DialogFragment` without out calling `requestInAppMessageRefresh` since it has been deprecated!

**Comment by briancaw** [comment]
Hi @ernestkamara 

Thanks for reaching out.  Can you let us know some further info to help us debug:

1) The SDK version you're using
2) Any logcat logs when the second IAM should be triggering (and if you could turn on your logging to verbose by setting `AppboyLogger.LogLevel = Log.VERBOSE;` in your application `onCreate()`.
3) A link to the campaigns used

Note that if the above items don't lead to a resolution, it'll also be useful to have:
1) A video reproduction of the issue
2) An APK that the issue can be reproduced on.

Thanks,
Brian

**Comment by ernestkamara** [comment]
Hi @briancaw 
Thanks for the quick response.
I am using Appboy v1.16.0 and a here link the to the second [campaign](https://dashboard.appboy.com/engagement/campaigns/584fdd8656ec317ebe6cc4cf/573031f5dfc3b43fcebb07e5?page=-2&campaignName=Item%20page%20on-boarding) 
Here is the [logs.txt](https://github.com/Appboy/appboy-android-sdk/files/661552/logs.txt) and also a link to a [video](https://www.dropbox.com/s/3eltrysy40g662y/appboy-on-boarding.mp4?dl=0)

**Comment by ernestkamara** [comment]
As you can see from the logs, `accept_terms` is the first trigger while `preview_item_page` is the second trigger

**Comment by Bucimis** [comment]
Hi @ernestkamara 

Thanks for sending these logs over.  This is Jared from the Android team.

A few notes:

1) As you noticed, the `preview_item_page` in-app message is initially not displaying because the minimum time interval between triggered actions is not met. The minimum interval is 30 seconds by default to avoid spamming users with messages but can be customized in your `appboy.xml` like so: `<integer name="com_appboy_trigger_action_minimum_time_interval_seconds">5</integer>` <- this example changes the interval to 5, but any value is possible, including 0.

2) When the `preview_item_page` in-app message is finally fired, we noticed that it was being fired on four in-app message subscribers.  

```
12-19 17:12:52.062 23894-23894/net.zedge.snakk D/Appboy v1.16.0 .bo.app.bc: Triggering com.appboy.events.InAppMessageEvent on 4 subscribers.
```

A typical integration would only have one subscriber at a time - do you have any special subscription or in-app message manager registration logic?  It would be good to make sure that any custom in-app message listeners on your end are unsubscribed correctly.

3) Regarding Dialogs, unfortunately we don't support displaying in-app messages in Dialogs at this time.  The reason is that in-app messages are displayed as custom views in the window of the activity passed to Appboy's in-app message manager.  Because Dialogs are shown in a separate (i.e. their own) window on top of the activity window, Appboy has no way to access its window to display the custom view.  As a result, the in-app message appears "behind" the Dialog.

Note that since Fragments are displayed in the Activity window, in-app messages will display correctly on an activity with Fragments.

***

Apologies for some of these nits and inconveniences.  We'll be updating our documentation to make it clearer on these points as well.  Please let us know your followup thoughts/questions.

Thanks!
Jared

**Comment by ernestkamara** [comment]
Thanks @Bucimis,
Adding `com_appboy_trigger_action_minimum_time_interval_seconds ` works but didn't solve the issue. I guess you are correct about using dialogs. I will sync with my team on the way forward.
Btw, the production variant would only have one subscriber at a time. Its because of debugging i force subscribing multiple times.

I am really looking forward to updating your Android documentation 👍 . Been a while since it was updated.

**Comment by Bucimis** [comment]
Appreciate the constructive feedback @ernestkamara!  Thanks again and let us know if/when anything else comes up.

**Comment by ernestkamara** [comment]
Hi @Bucimis 
Does v2.0.4 of the SDK supports displaying in-app messages in DialogFragments?
Thanks!

**Comment by Bucimis** [comment]
Hi @ernestkamara,

Thanks for getting in touch.  Unfortunately we haven't made any changes to enable in-app messages within Dialogs.  The following quote is still applicable:

```
Regarding Dialogs, unfortunately we don't support displaying in-app messages in Dialogs at this time. The reason is that in-app messages are displayed as custom views in the window of the activity passed to Appboy's in-app message manager. Because Dialogs are shown in a separate (i.e. their own) window on top of the activity window, Appboy has no way to access its window to display the custom view. As a result, the in-app message appears "behind" the Dialog.
```

Feel free to describe the use-case you are hoping to implement and we would be more than happy to help think of alternative ways to accomplish it.

Thanks,
Jared
