### ISSUE TITLE
IAM not displayed 

### ISSUE THREAD

**Issue by FlorianBasso** [Appboy/appboy-android-sdk#88]
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/Android/) and am still experiencing the issue.

# Report

## What version of the Braze Android SDK are you using?
 
2.2.1

## What did you do?

I integrated Braze with the lifecycle listener and used automatic GCM push registration.

Then I call `registerActivityLifecycleCallbacks(new AppboyLifecycleCallbackListener());`
in my Application.onCreate() method.

Then I tried to test an IAM, I received the push on my device that say : 
`Appboy Test Send`
`Click to see Test In-App Message`

Then I clicked on it.

## What did you expect to happen?

 The Braze SDK is integrated properly and creating sessions then I expect to see an IAM on my app.

## What happened instead?

 The Braze SDK doesn't create any sessions for the test user and I don't see any IAM on my app.

## Steps to reproduce

- Adds `registerActivityLifecycleCallbacks(new AppboyLifecycleCallbackListener());` on Application.onCreate()
- Start the app
- Creates a IAM in Braze admin website
- Send it to your user in mobile app
- A push is received to test IAM
- I clicked on it
- My app is launched 
- In-app message doesn't appear

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?

No

**Comment by radixdev** [comment]
Hello @FlorianBasso ,

Thanks for filing this issue. In order to properly debug, we'll need some information that may better be suited over email. Can you email support@braze.com and include the:
1. Braze campaign URL used to test
2. [Verbose logging](https://www.braze.com/documentation/Android/#verbose-logging) starting from when the app is started to after the IAM does not display?
3. An apk that our support team can use to reproduce the issue.

Thank you,
Appboy Android Team

**Comment by FlorianBasso** [comment]
Already 2 weeks passed, I still don't know if the support team has received the APK and the logs message I sent...

**Comment by Bucimis** [comment]
Hi @FlorianBasso,

Thanks again for getting in touch.  The associated ticket was marked as resolved in Desk, so closing here as well. 

Feel free to rep-open if this was in error.

Thanks,
Braze SDK Engineering
